casdoor:
    endpoint: https://door.casdoor.net
    clientId: 0ba528121ea87b3eb54d
    clientSecret: 04f4ca22101529a3503d5a653a877b4e8403edf0
    organization: casbin
    application: app-casbin-oa
intercept:
    proxyPort: 9090
    failClosedOnPdpError: true
    passthroughUnrecognized: true
    stepUpDefaultAction: deny
